function(getSubDir SUB_DIRS DIR)
    file(GLOB DIR_FILES LIST_DIRECTORIES true RELATIVE ${DIR} ${DIR}/*)
    foreach(DIR_FILE ${DIR_FILES})
        if(IS_DIRECTORY ${DIR}/${DIR_FILE} AND EXISTS ${DIR}/${DIR_FILE}/CMakeLists.txt)
            list(APPEND ${SUB_DIRS} ${DIR_FILE})
        endif()
    endforeach()
    return(PROPAGATE ${SUB_DIRS})
endfunction()
